---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: no

dotfiles_repo: https://github.com/cgrice/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/src/dotfiles
dotfiles_files:
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - zsh-completions
  - git
  - nvm
  - openldap
  - libiconv
  - php
  - wget
  - python
  - zsh
  - terraform


homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - visual-studio-code
  - docker
  - slack
  - iterm2
  - skype-for-business
  - java
  - jetbrains-toolbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: 
  - name: awscli
    executable: pip3
  - name: aws-sam-cli
    executable: pip3
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
